[package]
name = "emu"
version = "0.0.0"
authors = ["Juici <juicy66173@gmail.com>"]
description = "Library for emulating DS."
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
rom = { path = "../rom" }

log = "0.4"
