[package]
name = "common"
version = "0.0.0"
authors = ["Juici <juicy66173@gmail.com>"]
description = "Library of common code shared across the project."
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false
